# Týden 11. NumPy

## Instalace

NumPy lze nainstalovat pomocí pip nebo conda. Pokud jste instalovali Python pomocí Anaconda Distribution - je velice pravděpodbné, že již máte NumPy nainstalované ve vychozím prostředí.

### Pip
Pokud používáte pip, můžete NumPy nainstalovat pomocí terminálu:

```
pip install numpy
```

### Conda

Pokud používáte conda, můžete NumPy nainstalovat z výchozího nastavení:
```
conda install numpy
```

## Vícerozměrná pole

Hlavní datovou strukturou v `numpy` je `ndarray` (n-rozměrné pole), které umožňuje ukládat a manipulovat s homogenními daty pevné velikosti. Jedná se o tabulku prvků (obvykle čísel), všechny stejného typu, indexované dvojicí nezáporných celých čísel. V NumPy se dimenze nazývají osy (axes).

### Vytvoření pole

Pole můžete vytvořit například z běžného seznamu nebo tuple v pomocí funkce `array`. Typ výsledného pole se odvodí z typu prvků v posloupnostech.

In [10]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [8]:
a.dtype

dtype('int32')

In [11]:
b = np.array([1.2, 2.3, 3.4])
b.dtype

dtype('float64')

Funkce `array` transformuje posloupnosti posloupností na dvourozměrná pole, posloupnosti posloupností posloupností na třírozměrná pole atd.

In [13]:
c = np.array([(1.5, 2, 3), (4, 5, 6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Typ pole lze také explicitně zadat při jeho vytvoření:

In [14]:
d = np.array([[1, 2], [3, 4]], dtype=complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### Prázdná a záastupná pole

Často neznáme původní prvky pole, ale známe jeho velikost. Proto NumPy nabízí několik funkcí pro vytváření polí s počátečním zástupným obsahem. Ty minimalizují nutnost zvětšování polí, což je nákladná operace.

Funkce `zeros` vytvoří pole plné nul:

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Funkce `ones` vytvoří pole plné jedniček:

In [16]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Funkce `empty` vytvoří pole, jehož počáteční obsah je náhodný a závisí na stavu paměti. Ve výchozím nastavení je `dtype` vytvořeného pole `float64`, ale lze jej určit pomocí argumentu `dtype`.

In [17]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Pro vytváření posloupností čísel nabízí NumPy funkci `arange`, která je analogická vestavěné funkci Pythonu `range`, ale vrací numpy pole.

In [18]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

Při použití `arange` s `float` argumenty není obecně možné předpovědět počet získaných prvků kvůli konečné přesnosti v plovoucí desetinné čárce. Z tohoto důvodu je obvykle lepší použít místo `arange` funkci `linspace`, která dostane jako argument požadovaný počet prvků:

In [21]:
np.linspace(0, 2 * np.pi, 6)

array([0.        , 1.25663706, 2.51327412, 3.76991118, 5.02654825,
       6.28318531])

## Základní operace

Aritmetické operátory na polích se uplatňují *po prvcích*. Vytvoří se nové pole a naplní se výsledkem.

In [31]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [32]:
c = a - b
c

array([10, 19, 28, 37])

In [33]:
b**3

array([ 0,  1,  8, 27], dtype=int32)

In [34]:
5 * np.cos(a)

array([-4.19535765,  2.04041031,  0.77125725, -3.33469031])

In [35]:
a < 30

array([ True,  True, False, False])

Na rozdíl od mnoha maticových jazyků (jako MATLAB) pracuje operátor součinu `*` v polích NumPy po prvcích. Maticový součin lze provést pomocí operátoru `@` nebo funkce `dot`:

In [37]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A * B)           # elementwise product
print(A @ B)           # matrix product
print(np.dot(A, B))    # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


Při práci s poli různých typů odpovídá typ výsledného pole obecnějšímu nebo přesnějšímu typu (chování známé jako upcasting).

In [38]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
c = a + b
c.dtype

dtype('float64')

Mnoho unárních operací, například výpočet součtu všech prvků pole, je implementováno jako metody třídy `ndarray`.

In [42]:
a = np.random.random((2, 3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.279784   0.21272326 0.58962025]
 [0.35265034 0.51394912 0.66181367]]
2.61054064075441
0.2127232569371903
0.6618136662787595


Ve výchozím nastavení se tyto operace použijí na pole, jako by se jednalo o seznam čísel, bez ohledu na jeho tvar. Zadáním parametru `axis` však můžete použít operaci podél zadané osy pole:

In [44]:
print(a.sum(0))     # sum of each column
print(a.sum(1))     # sum of each row

[0.63243434 0.72667238 1.25143392]
[1.08212751 1.52841313]


## Univerzální funkce

NumPy poskytuje známé matematické funkce, jako jsou `sin`, `cos` a `exp`. V NumPy se nazývají "univerzální funkce" (`ufunc`). V NumPy tyto funkce pracují s polem po prvcích a na výstupu vytvářejí pole.

In [45]:
A = np.arange(3)
print(np.exp(A))
print(np.sqrt(A))

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


## Indexování, slicing a iterace

Jednorozměrná pole lze indexovat, slicovat a iterovat nad nimi podobně jako nad seznamy a jinými Python posloupnostmí.

In [46]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
a[5]

25

In [48]:
a[1:6]

array([ 1,  4,  9, 16, 25])

In [50]:
a[:8:2]

array([ 0,  4, 16, 36])

In [51]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

Vícerozměrná pole mohou mít na každé ose jeden index. Tyto indexy se uvádějí v tuplech oddělených čárkami:

In [54]:
b = np.array([[ 0,  1,  2,  3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33]])

b[2, 3]

23

In [56]:
b[:, 0]

array([ 1, 11, 21, 31])

In [57]:
b[1, :]

array([10, 11, 12, 13])

In [58]:
b[0:5, 2:4]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33]])

Iterace nad vícerozměrnými poli se provádí s ohledem na první osu:

In [59]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]


Pokud však chceme provést operaci nad každým prvkem pole, můžeme použít atribut `flat`, který je iterátorem nad všemi prvky pole:

In [60]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33


## Manipulace s tvarem

Tvar pole lze měnit pomocí různých příkazů. Všimněte si, že všechny tři následující příkazy vracejí upravené pole, ale původní pole nemění:

In [61]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33])

In [63]:
b.T

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33]])

In [62]:
b.reshape(8, 2)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13],
       [20, 21],
       [22, 23],
       [30, 31],
       [32, 33]])

Na rozdíl od metody `reshape` metoda `ndarray.resize` upravuje samotné pole:

In [64]:
b.resize(2, 8)
b

array([[ 0,  1,  2,  3, 10, 11, 12, 13],
       [20, 21, 22, 23, 30, 31, 32, 33]])

Pokud je při operaci přetváření zadán rozměr `-1`, ostatní rozměry se automaticky dopočítají:

In [66]:
b.reshape(4, -1)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

## Skládání různých polí

Several arrays can be stacked together along different axes:

In [67]:
a = np.array([[1., 2.],
              [3., 4.]])
b = np.array([[5., 6.],
              [7., 8.]])

print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


## Kopie a náhledy
Při práci s poli a manipulaci s nimi se jejich data někdy kopírují do nového pole a někdy ne. Existují tři případy:
1. Při jednoduchém přiřazení se objekty ani jejich data nekopírují. Tedy `a` a `b` jsou dvě jména pro stejný objekt ndarray:

In [70]:
a = np.array([[ 0,  1,  2],
              [ 3,  4,  5]])

b = a
b[0,0] = 10
a

array([[10,  1,  2],
       [ 3,  4,  5]])

2. Různé objekty pole mohou sdílet stejná data. Metoda `view` vytvoří nový objekt, který se dívá na stejná data.

In [79]:
c = a[:2,:2].view()
c

array([[10,  1],
       [ 3,  4]])

In [80]:
c[1, 1] = 20
a

array([[10,  1,  2],
       [ 3, 20,  5]])

3. Metoda `copy` vytvoří úplnou kopii pole a jeho dat.

In [81]:
d = a.copy()  
d[0, 0] = 30
a

array([[10,  1,  2],
       [ 3, 20,  5]])

## Pravidla vysílání

Při práci se dvěma poli NumPy porovnává jejich tvary po prvcích. Začíná od posledního (tj. nejpravějšího) rozměru a postupuje doleva. Dva rozměry jsou kompatibilní, když
 - jsou stejné, nebo
 - jeden z nich je roven 1.


 - Pole s velikostí `1` podél určitého rozměru se chovají, jako by měla velikost pole s největším tvarem podél tohoto rozměru. U "vysílaného" pole se předpokládá, že hodnota prvku pole je podél tohoto rozměru stejná.

In [82]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])

b = np.array([1, 2, 3])

a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [83]:
c = np.array([1, 2, 3, 4])
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

## Cvičení
V tomto cvičení provedeme následující operace pomocí numpy:
- Vytvořte jednorozměrné náhodné pole `a` délky 12.

- Vypiště pole `a` a jeho datový typ.

- Přetvořte pole `a` na dvourozměrné pole tvaru `(3, 4)`, a vytískněte nové pole.


- Vytvořte nové 2-rozměrné pole stejného tvaru pomoci funkcí `arange`.


- Proveďte sčítání dvou polí po prvcích a vytiskněte výsledek.

- Výpočtěte součet všech prvků výsledného pole.

- Výpočtěte střední hodnoty každého sloupce výsledného pole.