# Domácí úkol.

Importujte balíček numpy pod názvem `np`.

Vytvořte nulový vektor o velikosti 10

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Vytvořte nulový vektor o velikosti 10, ale s pátou hodnotou, která je 1.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Vytvořte vektor s hodnotami v rozmezí od 10 do 49.

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Obráťte vektor (z prvního prvku se stane poslední)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Vytvořte matici 3x3 s hodnotami od 0 do 8.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Zjistěte indexy nenulových prvků z [1,2,0,0,4,0]

(array([0, 1, 4], dtype=int64),)


Vytvořte matici identity 3x3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Vytvořte pole 3x3x3 s náhodnými hodnotami

[[[0.99552341 0.23686817 0.7177527 ]
  [0.25097026 0.96881725 0.6180598 ]
  [0.97860649 0.89777377 0.90080272]]

 [[0.02804093 0.75976767 0.72061065]
  [0.27419695 0.39744822 0.47830869]
  [0.68453445 0.0176976  0.03071968]]

 [[0.90584261 0.26111708 0.27042056]
  [0.79581124 0.86962789 0.56992518]
  [0.20568471 0.61427053 0.46778917]]]


Vytvořte pole 10x10 s náhodnými hodnotami a zjistěte minimální a maximální hodnotu

0.0070439670475411775 0.9715838936293097


Vytvořte náhodný vektor o velikosti 30 a zjistěte střední hodnotu

0.5345685106564491


Vytvoření 2d pole s 1 na okraji a 0 uvnitř

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Jak přidat rámeček (vyplněný nulami) kolem existujícího pole? Nápověda: použijtě funkci `pad()`

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Vytvořte matici 5x5 s hodnotami 1,2,3,4 těsně pod diagonálou. Nápověda: použijtě funkci `diag()`

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Vytvořte matici 8x8 a vyplňte ji šachovnicovým vzorem.

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Vynásobte matici 5x3 maticí 3x2 (součin reálných matic)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Jak najít společné hodnoty dvou polí? Nápověda: pomocí funkce `intersect1d()`

[8 6 0 0 3 2 6 6 6 5]
[7 2 1 1 6 4 7 1 7 3]
[2 3 6]


Jak získat data včerejška, dneška a zítřka? Nápověda: pomocí datetime64() a timedelta64()

2023-07-23 2023-07-24 2023-07-25


Jak získat všechna data odpovídající červenci 2016?

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


Vytvořte matici 5x5 s hodnotami řádků od 0 do 4

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Vytvořte náhodný vektor o velikosti 10 a nahraďte maximální hodnotu hodnotou 0

[0.11136939 0.36914852 0.         0.51999776 0.80306176 0.07528051
 0.87229587 0.43243835 0.18911197 0.38456175]
