# Week 4. The Numpy library.
Here we will learn the basics of Numpy. If you run in any trouble, you can always refer to the Numpy documentation (https://numpy.org/doc/stable/).
## Installation
If you haven't installed Numpy yet, you could do it in the following steps. Do only the steps under `Conda` if you use the Anaconda distribution, and otherwise, do the steps under `Pip` if you installed Python 3 directly. Skip all of this if you use Colab.
### Conda
If you use conda, you can install NumPy by running the following cell:

In [ ]:
# Best practice, use an environment rather than install in the base env. 
# You can use this 'my-env' environment to install more packages later.
!conda create -n my-env
!conda activate my-env
# If you want to install from conda-forge
!conda config --env --add channels conda-forge
# The actual install command
%conda install numpy

### Pip
If you use `pip`, you can install NumPy with:

In [ ]:
# Best practice, use an environment rather than install in the base env. 
# You can use this 'my-env' environment to install more packages later.
%pip install virtualenv
#Replace '/full/path/to/' with the full path to the folder where you want to create the virtual environment
!virtualenv /full/path/to/my-env
#Activate the virtual environment, don't forget to change the path:
!source /full/path/to/my-env/bin/activate
# The actual install command
%pip install numpy

## Import
Now we can run the following code to import the Numpy library. Tthe imported name is shortened to np for better readability. This is a widely adopted convention, so always use `import numpy as np`.

In [1]:
import numpy as np

## Numpy arrays
The numpy array, called `ndarray`, is a central class of the NumPy library.  One (but not the only) way we can initialize NumPy arrays is from Python lists or tuples:

In [13]:
#Write the desired array as a list
vector_as_list = [1., 2., 3.]
#Convert the list into the Numpy array
vector_as_array = np.array(vector_as_list)
vector_as_array

array([1., 2., 3.])

We can, of course, write the list directly into the `np.array()` function. See how we can initialize a 3x2 matrix, which is a list of lists:

In [14]:
matrix = np.array([[1., 2., 3.], [4., 5., 6.]])
matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

You can create placeholder arrays filled with ones, zeros, or diagonal ($I$) ones.

In [8]:
#Create a 3x2 array filled with zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
#Create a 3d 2x3x3 array filled with ones of integer type
np.ones((2, 3, 3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [15]:
#Create an eye matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#Create an array as a sequence of numbers
np.arange(5, 30, 5)

array([ 5, 10, 15, 20, 25])

In [17]:
#Create an array as a sequence of numbers with a predefined number of steps
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

You can also the `reshape()` method to change the dimension of your array, make sure that the total number of elements is the same:

In [21]:
np.linspace(1, 2, 9).reshape(3, 3)

array([[1.   , 1.125, 1.25 ],
       [1.375, 1.5  , 1.625],
       [1.75 , 1.875, 2.   ]])

## Indexing
One-dimensional arrays are be indexed and sliced the same as Python lists:

In [25]:
a = np.arange(10)
print(a)
print(a[2])
print(a[2:5])
print(a[-2])

[0 1 2 3 4 5 6 7 8 9]
2
[2 3 4]
8


Multidimensional arrays can have one index per axis. These indices are separated by commas:

In [45]:
b = np.linspace(1, 16, 16).reshape(4, 4)
print(b, '\n')

print(b[2, 3], '\n')    # the element of b in the 3rd row, 4th column
print(b[0:4, 1], '\n')  # each row in the second column of b
print(b[:, 1], '\n')    # equivalent to the previous example
print(b[1:3, :], '\n')  # each column in the second and third row of b
print(b[-1], '\n')      # the last row. Equivalent to b[-1, :]
print(b.flat[14])       # the 15th element of the matrix

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]] 

12.0 

[ 2.  6. 10. 14.] 

[ 2.  6. 10. 14.] 

[[ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 

[13. 14. 15. 16.] 

15.0


## Basic operations
Arithmetic operators on arrays apply **elementwise**. 

In [44]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, '\n')
print(b, '\n')

c = a + b       #add the arrays elementwise
print(c, '\n')

d = b ** 2      #square all the elements of b
print(d, '\n')

e = 10 * np.sin(a)
print(e, '\n')

f = a < 35
print(f)

[10 20 30 40] 

[0 1 2 3] 

[10 21 32 43] 

[0 1 4 9] 

[-5.44021111  9.12945251 -9.88031624  7.4511316 ] 

[ True  True  True False]


The product operator `*` also operates elementwise in NumPy arrays (unlike in MATLAB). The matrix product can be performed using the `@` operator or the `dot()` function or method:

In [47]:
A = np.array([[1, 0],
              [1, 1]])

B = np.array([[2, 3],
              [0, 4]])

C = A * B         # elementwise product
print(C, '\n')

D = A @ B         # matrix product
print(D, '\n')

E = np.dot(A, B)  # function for the matrix product
print(E, '\n')

F = A.dot(B)      # method for the matrix product
print(F)

[[2 0]
 [0 4]] 

[[2 3]
 [2 7]] 

[[2 3]
 [2 7]] 

[[2 3]
 [2 7]]


## Universal Functions
NumPy provides mathematical functions such as `sin`, `cos`, and `exp`. These functions operate elementwise on an array, producing an array as output.

In [48]:
a = np.arange(3)
print(a, '\n')

b = np.exp(a)
print(b, '\n')

c = np.sqrt(c)
print(c, '\n')

d = np.cos(c)
print(d, '\n')

[0 1 2] 

[1.         2.71828183 7.3890561 ] 

[3.16227766 4.58257569 5.65685425 6.55743852] 

[-0.99978607 -0.129449    0.8101836   0.96262772] 

